version: "3.9"

services:

  db:
    image: "postgis/postgis"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 8
  
  api:
    build: .
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
    environment:
      - DEBUG=1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_SERVER=db:5432
      - POSTGRES_DB=postgres

    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: